### ISSUE TITLE
Number of epochs does not match the description in the paper

### ISSUE THREAD

**Issue by licj15** [zhihao-lin/neurmips#4]
Dear Authors,

Thank you for the great work and the open-sourced code!

I noticed that the number of epochs in the configs does not match the description in the paper.

In the [camera version](https://openaccess.thecvf.com/content/CVPR2022/papers/Lin_NeurMiPs_Neural_Mixture_of_Planar_Experts_for_View_Synthesis_CVPR_2022_paper.pdf): it is said that "We first train the teacher model for **6K** epochs, then we distill the planar experts for **1.5K** epochs. Finally, we fine-tune the experts for **2.5K** epochs."

However, in the [config for replica dataset](https://github.com/zhihao-lin/neurmips/blob/main/configs/replica-room0.yaml#L62-L67):
```
  epoch:
    teacher: 2000
    distill: 1000
    finetune: 1000
```
in the [config for tat dataset](https://github.com/zhihao-lin/neurmips/blob/main/configs/tat-barn.yaml#L62-L67):
```
  epoch:
    teacher: 2800
    distill: 1000
    finetune: 3500
```
, none of them matches the description in the paper.

I was wondering whether it is a typo in the paper or the currently open-sourced configs are not for those PSNR numbers reported in the paper?

Thank you!
